version: '2'
services:
    sun-app:
        image: sun
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sun-mysql:3306/sun?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sun-mysql:
        extends:
            file: mysql.yml
            service: sun-mysql
